import Head from 'next/head'
import PrimaryLayout from '../components/PrimaryLayout'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PrimaryLayout>
        <h1>Home</h1>
      </PrimaryLayout>
    </>
  )
}
